language: r
cache: packages
r:
  - oldrel
  - release
  - devel

sudo: false

warnings_are_errors: true

r_build_args: 

r_packages:
  - rmarkdown
  - covr

r_check_args: --as-cran

after_success:
  - Rscript -e 'library(covr);codecov()'

notifications:
  email:
    on_success: change
    on_failure: change

env:
  before_install: echo "options(repos = c(CRAN='http://cran.rstudio.com'))" > ~/.Rprofile